# Generated by Django 5.1.4 on 2025-03-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='сreated_at',
            new_name='created_at',
        ),
    ]
